import React from "react";
import Head from "next/head";

import {
  getVacancies,
  DEFAULT_SEARCH_PARAMS,
} from "@/features/shared/api/superjob/hooks";
import { useFavorites } from "@/features/shared/components/FavoritesProvider";

import { FavoritesList } from "@/features/favorites/components/FavoritesList";

import { dehydrate, QueryClient, DehydratedState } from "@tanstack/react-query";
import { GetServerSideProps } from "next";

export const getServerSideProps: GetServerSideProps<{
  dehydratedState: DehydratedState;
}> = async ({ req }) => {
  const isFirstServerCall = !req?.url?.startsWith("/_next/data/");
  const favoritesFromCookie = JSON.parse(
    req.cookies.favorites || "[]"
  ) as Array<number>;
  const queryClient = new QueryClient();

  if (isFirstServerCall) {
    await queryClient.prefetchQuery(
      ["vacancies", { ids: favoritesFromCookie, ...DEFAULT_SEARCH_PARAMS }],
      () => getVacancies({ ids: favoritesFromCookie, ...DEFAULT_SEARCH_PARAMS })
    );
  }

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
      favorites: JSON.parse(req.cookies.favorites || "[]"),
    },
  };
};

export function Page() {
  const favorites = useFavorites();

  const filters = React.useMemo(() => ({ ids: favorites.values }), [favorites]);

  return (
    <>
      <Head>
        <title>Superjob - Favorites</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {favorites.values.length !== 0 && <FavoritesList filters={filters} />}
    </>
  );
}
