import React from "react";
import { GetServerSideProps } from "next";
import Head from "next/head";
import { dehydrate, QueryClient, DehydratedState } from "@tanstack/react-query";

import {
  getVacancies,
  DEFAULT_SEARCH_PARAMS,
} from "@/features/shared/api/superjob/hooks";

import { VacanciesList } from "@/features/search/components/VacanciesList";
import { SearchForm } from "./components/SearchForm";

export const getServerSideProps: GetServerSideProps<{
  dehydratedState: DehydratedState;
}> = async ({ req }) => {
  const isFirstServerCall = !req?.url?.startsWith("/_next/data/");
  const queryClient = new QueryClient();

  if (isFirstServerCall) {
    await queryClient.prefetchQuery(["vacancies", DEFAULT_SEARCH_PARAMS], () =>
      getVacancies(DEFAULT_SEARCH_PARAMS)
    );
  }

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  };
};

export function Page() {
  const [searchQuery, setSearchQuery] = React.useState("");

  const filters = React.useMemo(
    () => ({
      keyword: searchQuery,
    }),
    [searchQuery]
  );

  return (
    <>
      <Head>
        <title>Superjob - Search</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SearchForm initialValue={""} onSubmit={setSearchQuery} />
      <VacanciesList filters={filters} />
    </>
  );
}
