import React from "react";
import { GetServerSideProps } from "next";
import Head from "next/head";
import { dehydrate, QueryClient, DehydratedState } from "@tanstack/react-query";

import { DEFAULT_SEARCH_PARAMS } from "@/features/shared/api/superjob/hooks";

import { getVacancies } from "../shared/api/superjob/requests";

import { VacanciesList } from "@/features/search/components/VacanciesList";
import { SearchForm } from "./components/SearchForm";

import { getAuthAxiosConfig } from "../shared/helpers/auth";

export const getServerSideProps: GetServerSideProps<{
  dehydratedState: DehydratedState;
}> = async ({ req, res }) => {
  const isFirstServerCall = !req?.url?.startsWith("/_next/data/");
  const queryClient = new QueryClient();
  const { headers, transformRequest } = getAuthAxiosConfig(req, res);

  if (isFirstServerCall) {
    await queryClient.prefetchQuery(
      ["vacancies", { ...DEFAULT_SEARCH_PARAMS, keyword: "" }],
      () =>
        getVacancies({
          params: { ...DEFAULT_SEARCH_PARAMS, keyword: "" },
          headers,
          transformRequest,
        })
    );
  }

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
      favorites: JSON.parse(req.cookies.favorites || "[]"),
    },
  };
};

export function Page() {
  const [searchQuery, setSearchQuery] = React.useState("");

  const filters = React.useMemo(
    () => ({
      keyword: searchQuery,
    }),
    [searchQuery]
  );

  return (
    <>
      <Head>
        <title>Superjob - Search</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SearchForm initialValue={""} onSubmit={setSearchQuery} />
      <VacanciesList filters={filters} />
    </>
  );
}
