import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

import { VacanciesList } from "@/features/shared/components/VacanciesList";
import {
  getVacancies,
  DEFAULT_SEARCH_PARAMS,
} from "@/features/shared/components/VacanciesList/hooks";

const inter = Inter({ subsets: ["latin"] });

import { dehydrate, QueryClient, useQuery } from "@tanstack/react-query";

export async function getServerSideProps() {
  const queryClient = new QueryClient();

  await queryClient.prefetchQuery(["vacancies", DEFAULT_SEARCH_PARAMS], () =>
    getVacancies(DEFAULT_SEARCH_PARAMS)
  );

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  };
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <VacanciesList />
      </main>
    </>
  );
}
